# 配置数据库的连接信息 - 四要素
spring:
  datasource:
    dynamic:
      primary: master # 指定默认数据源名
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/vocabulary_punch
          username: root
          password: 123456
server:
  # 端口号
  port: 9002